### ISSUE TITLE
Can't download train and test data

### ISSUE THREAD

**Issue by JalonZhou** [henriblancke/neural-chat#1]
File "s3.py", line 100, in <module>
    retrieve_data()
  File "s3.py", line 56, in retrieve_data
    files = s3.list_objects(Bucket=BUCKET_NAME)['Contents']
  File "/home/jalon/anaconda3/envs/tf1.0/lib/python3.5/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/jalon/anaconda3/envs/tf1.0/lib/python3.5/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by henriblancke** [comment]
Hi @JalonZhou if you add your AWS credentials in the `s3.py` file you'll be able to download the test and train data. Let me know if you run into any problems.

**Comment by otherdcn** [comment]
Hi @henriblancke, I've been playing around with your repo and I'm stuck at the same place as @JalonZhou, that is "The AWS Access Key Id you provided does not exist in our records". Do you by any chance have "temporary security credentials" that I could use?

**Comment by henriblancke** [comment]
Hi @dan-97, thanks for giving it a try! If you set the following in the `s3.py` file to your AWS credentials it should work.

```python
AWS_ACCESS_KEY = 'your_access_key'
AWS_SECRET_KEY = 'your_secret_key'
```
Let me know if it doesn't.

**Comment by otherdcn** [comment]
Thanks, it works...
